### ISSUE TITLE
Download method listed in API docs but not available in client

### ISSUE THREAD

**Issue by agoddijn** [redivis/redivis-python#18]
The download method on the Table object is [listed in the API docs](https://apidocs.redivis.com/examples/downloading-data) to download full tables in specific formats but missing from the Python client. The documentation for downloading via a REST API endpoint mentioned [here](https://apidocs.redivis.com/rest-api/tables/listrows) is also [missing](https://docs.redivis.com/projects/saving-and-exporting)

I'm also getting the following error when trying to use `to_dataframe` and `get`

`SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))`

Would be great if one of these methods could be made available. I'd like to download a demo table using an API call (preferably a rest API call)

Let me know if I should be asking somewhere else / someone else :)

**Comment by imathews** [comment]
Hi @agoddijn - thanks for filing this issue! Apologies, this was a documentation error — that example page was out of date (it's been removed), all python related examples can be found [here](https://apidocs.redivis.com/client-libraries/redivis-python/examples).

The currently recommended way to pull data out of Redivis is via the `listRows` endpoint (and corresponding methods in python/R/Node.js), but we can definitely consider implementing an export interface similar to what's offered in the UI. If you could provide details about your use case here, it would definitely be helpful in understanding and prioritizing this feature. 

Thanks!

**Comment by agoddijn** [comment]
No worries, thanks for the response! 

In our use case we want to pull full example OMOP datasets onto our platform in an automated fashion (in case there are any updates). We could do it through the frontend by just downloading the dataset and then uploading to our platform but it's not a reproducible process. We'd rather pull in data either through a REST API call or through a python script if possible.

**Comment by imathews** [comment]
Got it, thanks, this is helpful. I'll update this issue if there are any updates to this functionality. As an FYI, we will likely need to implement egress quotas (or fees) for large data exports, as the cloud fees for such egress can be non-trivial.
