### ISSUE TITLE
`query.to_dataframe` throws for empty results

### ISSUE THREAD

**Issue by stevejpurves** [redivis/redivis-python#28]
When performing a query that results in an empty list, for example a geospatial query:

```
POINT_OUTSIDE="POINT(-119.85281782098426 36.4839598390287)"

q = dataset.query(f"""
    SELECT DISTINCT ID, NAME from Survey s
    WHERE ST_Contains(s.geometry, st_geogfromtext("{POINT_OUTSIDE}"))
""")

df = q.to_dataframe()
print("Point is outside, expect no results")
df.head()
```

If this returns no rows, the call to `q.to_dataframe()` will throw an `IndexError: list index out of range` error. In contrast `q.list_rows()` just returns an empty list.

Expected behaviour would be to return None or an empty dataframe

**Comment by imathews** [comment]
Thanks @stevejpurves for filing this bug. This issue should now be resolved in the latest release (`0.8.2`)
