### ISSUE TITLE
Unable to write to tempdir on windows

### ISSUE THREAD

**Issue by imathews** [redivis/redivis-python#34]
We're not using proper cross-platform filepaths; e.g.: https://github.com/redivis/redivis-python/blob/main/src/redivis/common/list_rows.py#L97

Probably just need to use a proper path library rather than string interpolation.

**Comment by jbiggsets** [comment]
Hello! I submitted a PR (#35) to hopefully address this issue. (I was trying to use the client on a Windows machine and run into this same bug.)

**Comment by imathews** [comment]
Closed in #35, released in `0.12.5`
