### ISSUE TITLE
"allow line breaks in cells" parameter for table.upload

### ISSUE THREAD

**Issue by bchivers-stanford** [redivis/redivis-python#6]
In both the UI of Redivis and the [API](https://apidocs.redivis.com/resource-definitions/upload), there is an option to `allowQuotedNewLines` when uploading data.  

In the python package, this parameter doesn't exist for [`table.upload`](https://github.com/redivis/redivis-python/blob/cdbe791557b78cf9c6bb7700c062ce86a2751730/redivis/classes/Table.py#L97).  

This would be a great addition to allow the upload of files containing new lines via python.

**Comment by imathews** [comment]
Thanks @bchivers-stanford! This should now be resolved with the latest release; you'll want to do a `pip install --upgrade redivis`.

The `table.upload()` method now accepts all parameters supported by the API, documented [here](https://app.gitbook.com/o/-LAzxbDPgjEGJfV0tvZu/s/-LVomwsv-Jki4ugGCwwN/client-libraries/redivis-python/reference#table.upload-name-data-type-has_header_row-true-skip_bad_records-false-allow_quoted_newlines-false-q). (Side note — we'll be improving this documentation soon, it's pretty bare bones atm)
